// const categories = [
//     {
//         id: 1,
//         category: "Pizzas",
//         slug: "pizza",
//     },
//     {
//         id: 2,
//         category: "Sides",
//         slug: "sides",
//     },
//     {
//         id: 3,
//         category: "Pasta",
//         slug: "pasta",
//     },
//     {
//         id: 4,
//         category: "Salads",
//         slug: "salads",
//     },
//     {
//         id: 5,
//         category: "Drinks",
//         slug: "drinks",
//     },
//     {
//         id: 6,
//         category: "Desserts",
//         slug: "desserts",
//     },
//     {
//         id: 7,
//         category: "Sauces",
//         slug: "sauces",
//     },
//     {
//         id: 8,
//         category: "Papadias",
//         slug: "papadias",
//     },
// ];
const categories = ["pizza", "sides", "pasta", "salads", "drinks", "desserts", "sauces", "papadias"];

const food = {
    pizza: [
        {
            title: "Chicken Parmesan",
            composition: "Pizza Sauce, Garlic Sauce, Chicken Poppers, Mushrooms, Mozzarella, Italian Flavoring",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_b13328cf37671350c49a3d6644504d39.jpg",
            price: 11,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 17, size: "Medium, 30 cm" },
                { type: "Traditional", price: 21, size: "Large, 35 cm" },
                { type: "Thin", price: 17, size: "Medium, 30 cm" },
                { type: "Thin", price: 21, size: "Large, 35 cm" },
            ],
            id: "eqtdV7d1X33VkB9rOC_Jd",
        },
        {
            title: "Grill Chicken Parmesan",
            composition: "Pizza Sauce, Garlic Parmesan Sauce, Grilled chicken, Ham, Tomatoes, Mozzarella , Halapeno",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f077c7209864bc10ba687d9c5fd2bd54.jpg",
            price: 5.5,
            subcategory: ["hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 17, size: "Medium, 30 cm" },
                { type: "Traditional", price: 17, size: "Medium, 30 cm" },
                { type: "Traditional", price: 21, size: "Large, 35 cm" },
                { type: "Thin", price: 21, size: "Large, 35 cm" },
            ],
            id: "tMcRbeMZzjbSUWZVSmxAW",
        },
        {
            title: "American Hot",
            composition: "Pizza Sauce, Mozzarella, Pepperoni, Jalapeño Pepper",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ec836ad55fb828a2816c7f52d317cabb.jpg",
            price: 5.5,
            subcategory: ["hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 14, size: "Medium, 30 cm" },
                { type: "Traditional", price: 19, size: "Large, 35 cm" },
                { type: "Thin", price: 14, size: "Medium, 30 cm" },
                { type: "Thin", price: 19, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
            ],
            id: "4W3O5ET9thkewAEFAej-J",
        },
        {
            title: "Spicy Chicken Ranch",
            composition: "Ranch Sauce, Grilled Chicken, Mushroom, Jalapeño Pepper, Tomato, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_c74c8cc3aa537477ed5fdc54d3214e41.jpg",
            price: 5.5,
            subcategory: ["chicken", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "WI-lpUm85l7h9ToCWhdwJ",
        },
        {
            title: "Carnival",
            composition: "Pizza Sauce, Mushroom, Black Olive, Pepperoni, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_09e9a3d604c6811fe50a621c3d3940c8.jpg",
            price: 9,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 14, size: "Medium, 30 cm" },
                { type: "Traditional", price: 19, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
                { type: "Thin", price: 14, size: "Medium, 30 cm" },
                { type: "Thin", price: 19, size: "Large, 35 cm" },
            ],
            id: "lsfle5gwoS1JYOOYsOu4G",
        },
        {
            title: "NY Style pizza Margherita (40 cm)",
            composition: "Pizza Sauce, Mozzarella, Tomato, Oregano",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_6cc4d1e4fb49b0d8f707a952fc28d9d9.jpg",
            price: 20,
            subcategory: [],
            category: "pizza",
            id: "qlEY-kGyJBmXVMg7-aAlc",
        },
        {
            title: "NY Style Grill Chicken (40 cm)",
            composition: "Pizza Sauce, Grilled Chicken, Mozzarella, Tomato",
            img: "https://www.papajohns.az/images/Spaysi-Italyan-x%C4%B1r%C3%A7%C4%B1lt%C4%B1l%C4%B1-p-800.jpeg",
            price: 26,
            subcategory: [],
            category: "pizza",
            id: "hj1vpBBSiAHYkY9ql-BAp",
        },
        {
            title: "NY Style Pepperoni (40 cm)",
            composition: "Pizza Sauce, Pepperoni, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ce8525f0903364867882afc8ec572b98.jpg",
            price: 23,
            subcategory: [],
            category: "pizza",
            id: "RMgpKFeqlk4t9r-tVCQpF",
        },
        {
            title: "Cheddar Double Burger",
            composition: "1000 Island sauce, Beef, Tomato, Mozzarella, Cheddar",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_272af9ab17eaa7d57062c927e94164b1.jpg",
            price: 12,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 20, size: "Medium, 30 cm" },
                { type: "Traditional", price: 25, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 20, size: "Medium, 30 cm" },
                { type: "Thin", price: 25, size: "Large, 35 cm" },
            ],
            id: "vbXseAqErlzV8atr_-0My",
        },
        {
            title: "Chicken Ranch",
            composition: "Ranch sauce, Grilled Chicken, Tomato, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_a875457644d14093cd4bc0a47f647576.jpg",
            price: 5.5,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "OvMcW7F9wdM619lbtxc2S",
        },
        {
            title: "Papa Mix",
            composition: "Chicken BBQ, Hot & Spicy, Margherita, Classic Pepperoni",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_3156bc879a85a6fc09d57895cd45d04a.jpg",
            price: 20,
            subcategory: [],
            category: "pizza",
            variations: [
                {
                    type: "Traditional",
                    price: 20,
                    size: "Chicken BBQ, Hot & Spicy, Margherita, Classic Pepperoni0 ",
                },
            ],
            id: "FLvaQ4EYLwwfSZ07FaLxE",
        },
        {
            title: "Spicy Vegetarian",
            composition: "Pizza Sauce, Jalapeño Pepper, Tomato, Mushroom, Black Olive, Green Pepper, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_b410922d6c221fedffd15777f463bb02.jpg",
            price: 5.5,
            subcategory: ["vegan", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 13, size: "Medium, 30 cm" },
                { type: "Traditional", price: 18, size: "Large, 35 cm" },
                { type: "Thin", price: 13, size: "Small, 23 cm" },
                { type: "Thin", price: 18, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
            ],
            id: "WCKuOjBFVbt9JcwaXvYuh",
        },
        {
            title: "4 Cheese",
            composition: "Pizza sauce, Mozzarella, Feta, Parmesan and Cheddar Cheeses",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_5e5aaab1bded23b900fb49edce788888.jpg",
            price: 11,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "-aTxaJD9K03fV0couZBp-",
        },
        {
            title: "Cheddar Chicken Club",
            composition: "Pizza sauce, Grilled Chicken, Tomato, Ham, Mozzarella, Cheddar, Ranch sauce",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_12e23e16599c1a699587c3ec857fcb8f.jpg",
            price: 11,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 18, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 18, size: "Medium, 30 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
            ],
            id: "6aG4F1Sdx6hxSmpaxRomx",
        },
        {
            title: "Chicken Barbecue",
            composition: "Pizza sauce, Grilled Chicken, Mushroom, Barbecue Sauce, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_15135b56809cd2a5d12ca173e680e81e.jpg",
            price: 5.5,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "Jg8nHSg8MLUK9jrh0pAtH",
        },
        {
            title: "Mexican",
            composition: "Pizza sauce, Grilled Chicken, Tomato, Mushroom, Green Pepper, Jalapeño Pepper, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_b4765fad0ffac0ed9bf9b5c512ca552a.jpg",
            price: 5.5,
            subcategory: ["chicken", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 15, size: "Medium, 30 cm" },
                { type: "Traditional", price: 20, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
                { type: "Thin", price: 15, size: "Medium, 30 cm" },
                { type: "Thin", price: 20, size: "Large, 35 cm" },
            ],
            id: "J8FwVqgk3_iUbvYEXifSn",
        },
        {
            title: "Super Papa",
            composition: "Pizza sauce, Pepperoni, Italian Sausage, Ham, Mushroom, Black Olive, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_7fb7c5adb0f5a2b332b78dfa393f2378.jpg",
            price: 12,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 18, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 18, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "qaE-Gq9cxGDDmnCrQhN_L",
        },
        {
            title: "Greek",
            composition: "Pizza sauce, Tomato, Pepperoncini, Black Olive, Feta Cheese, Oregano, Mozzarella Cheese",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f537b94b02b4e15bf61f1aad74b7a77b.jpg",
            price: 8,
            subcategory: ["vegan", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 8, size: "Small, 23 cm" },
                { type: "Traditional", price: 13, size: "Medium, 30 cm" },
                { type: "Traditional", price: 16, size: "Large, 35 cm" },
                { type: "Thin", price: 8, size: "Small, 23 cm" },
                { type: "Thin", price: 13, size: "Medium, 30 cm" },
                { type: "Thin", price: 16, size: "Large, 35 cm" },
            ],
            id: "JTG9ZHwbk2D74rfg2T4kZ",
        },
        {
            title: "Chicken Cheeseburger",
            composition: "1000 Island sauce, Grilled Chicken, Pickles, Tomato, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_55dc22481753618bf6d61dfb087099f2.jpg",
            price: 12,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 19, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 19, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "MwbtxDjrw6WhJUbOeybs_",
        },
        {
            title: "Margherita",
            composition: "Pizza sauce, Tomato, Oregano, Extra Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f8da8b4b68e91c8a697aed2baf03f041.jpg",
            price: 5.5,
            subcategory: ["vegan"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 8, size: "Small, 23 cm" },
                { type: "Traditional", price: 13, size: "Medium, 30 cm" },
                { type: "Traditional", price: 16, size: "Large, 35 cm" },
                { type: "Thin", price: 8, size: "Small, 23 cm" },
                { type: "Thin", price: 13, size: "Medium, 30 cm" },
                { type: "Thin", price: 16, size: "Large, 35 cm" },
            ],
            id: "VvP2Artn-992jWOIlAjQ8",
        },
        {
            title: "Mixed Meat",
            composition: "Pizza sauce, Pepperoni, Italian Sausage, Beef, Ham, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_3905c3a91f3b9c786a289f6b8d9e6713.jpg",
            price: 14,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 14, size: "Small, 23 cm" },
                { type: "Traditional", price: 22, size: "Medium, 30 cm" },
                { type: "Traditional", price: 28, size: "Large, 35 cm" },
                { type: "Thin", price: 14, size: "Small, 23 cm" },
                { type: "Thin", price: 22, size: "Medium, 30 cm" },
                { type: "Thin", price: 28, size: "Large, 35 cm" },
            ],
            id: "rnc4l77WUYE8KPlG0Ot1k",
        },
        {
            title: "Vegetarian",
            composition: "Pizza sauce, Tomato, Mushroom, Green Pepper, Black Olive, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_e4f2d3721cdf82009bce80eed2ee655e.jpg",
            price: 5.5,
            subcategory: ["vegan"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 13, size: "Medium, 30 cm" },
                { type: "Traditional", price: 18, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
                { type: "Thin", price: 13, size: "Medium, 30 cm" },
                { type: "Thin", price: 18, size: "Large, 35 cm" },
            ],
            id: "KcO7mTzchPV4XpJ-vIEUQ",
        },
        {
            title: "Spicy Italian",
            composition: "Pizza sauce, Italian sausage, Pepperoni, Red Pepper Flakes, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ee1a9a36f2aab60de8e957a309976f07.jpg",
            price: 13,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 13, size: "Small, 23 cm" },
                { type: "Traditional", price: 21, size: "Medium, 30 cm" },
                { type: "Traditional", price: 27, size: "Large, 35 cm" },
                { type: "Thin", price: 13, size: "Small, 23 cm" },
                { type: "Thin", price: 21, size: "Medium, 30 cm" },
                { type: "Thin", price: 27, size: "Large, 35 cm" },
            ],
            id: "mabUrM4PThXfuxWZp271h",
        },
        {
            title: "Rustic",
            composition: "BBQ sauce, Italian sausage, Pepperoni, Mushroom, Green Pepper, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_adeb5a28a7792448f0ee2127948fa01c.jpg",
            price: 10,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 15, size: "Medium, 30 cm" },
                { type: "Traditional", price: 20, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 15, size: "Medium, 30 cm" },
                { type: "Thin", price: 20, size: "Large, 35 cm" },
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
            ],
            id: "lRL4SQrRYD_mHXuHmPb_a",
        },
        {
            title: "Mixed Meat BBQ",
            composition: "BBQ sauce, Italian sausage, Beef, Ham, Pepperoni, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_8a7726c327a867444654c77d733ea2c9.jpg",
            price: 15,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 15, size: "Small, 23 cm" },
                { type: "Traditional", price: 23, size: "Medium, 30 cm" },
                { type: "Traditional", price: 29, size: "Large, 35 cm" },
                { type: "Thin", price: 15, size: "Small, 23 cm" },
                { type: "Thin", price: 23, size: "Medium, 30 cm" },
                { type: "Thin", price: 29, size: "Large, 35 cm" },
            ],
            id: "0xw-QO-E30J_c-IQiTTV-",
        },
        {
            title: "Bonanza",
            composition: "BBQ sauce, Beef, Ham, Tomato, Mozzarella, Jalapeño Pepper",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_8a7726c327a867444654c77d733ea2c9.jpg",
            price: 13,
            subcategory: [],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 13, size: "Small, 23 cm" },
                { type: "Traditional", price: 20, size: "Medium, 30 cm" },
                { type: "Traditional", price: 25, size: "Large, 35 cm" },
                { type: "Thin", price: 13, size: "Small, 23 cm" },
                { type: "Thin", price: 20, size: "Medium, 30 cm" },
                { type: "Thin", price: 25, size: "Large, 35 cm" },
            ],
            id: "fwBriqYXxA0y7Uv4dcml_",
        },
        {
            title: "Double Cheeseburger",
            composition: "1000 Island sauce, Beef, Pickles, Tomato, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_394544511c5df922b24da5c78f5b3dd2.jpg",
            price: 12,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 19, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 19, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "4_e0cNmHzRfy8Eu0wrvTA",
        },
        {
            title: "Hawaiian",
            composition: "Pizza sauce, Grilled Chicken, Pineapple, Extra Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_245ffe808437b1c9e2d782bf320baa6c.jpg",
            price: 5.5,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 18, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 18, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "EoeQc7wZMPHHx6-URxVHL",
        },
        {
            title: "Western Barbecue",
            composition: "Beef, Mushroom, Barbecue Sauce, Mozzarella Cheese",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_7d15ebac61849618ea980d6c70b520bf.jpg",
            price: 5.5,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "p867Y-U9iR0UvgJt1wyNl",
        },
        {
            title: "Classic Pepperoni",
            composition: "Pepperoni, Extra Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_35c4eb8d6c59dd507e7cce1f2c15a987.jpg",
            price: 5.5,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 9, size: "Small, 23 cm" },
                { type: "Traditional", price: 14, size: "Medium, 30 cm" },
                { type: "Traditional", price: 19, size: "Large, 35 cm" },
                { type: "Thin", price: 9, size: "Small, 23 cm" },
                { type: "Thin", price: 14, size: "Medium, 30 cm" },
                { type: "Thin", price: 19, size: "Large, 35 cm" },
            ],
            id: "ZIvN-kGG6GsmYMvJm14J_",
        },
        {
            title: "Hot and Spicy",
            composition: "Pizza sauce, Beef, Tomato, Green Pepper, Jalapeño Pepper, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_4933b236cad07c946ddd5ea4b41cf1cf.jpg",
            price: 5.5,
            subcategory: ["meat", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 16, size: "Medium, 30 cm" },
                { type: "Traditional", price: 21, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 16, size: "Medium, 30 cm" },
                { type: "Thin", price: 21, size: "Large, 35 cm" },
            ],
            id: "bCcqe-4LcJscIHp-0itpH",
        },
        {
            title: "Marinara",
            composition: "Pizza sauce, Tuna, Green Pepper, Black Olive, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_c80b4c545b7e8884beded2d4c2f5551b.jpg",
            price: 5.5,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 5.5, size: "Mini, 17 cm" },
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 18, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 18, size: "Medium, 30 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "Pd01XJfzbdh-BOxDAyKG2",
        },
        {
            title: "Little Italy",
            composition: "Pizza sauce, Pepperoni, Italian Sausage, Mushroom, Black Olive, Oregano, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_6d96f0c3d4f91efe33b75e40d8a1ea0c.jpg",
            price: 11,
            subcategory: ["meat"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 11, size: "Small, 23 cm" },
                { type: "Traditional", price: 17, size: "Medium, 30 cm" },
                { type: "Traditional", price: 22, size: "Large, 35 cm" },
                { type: "Thin", price: 11, size: "Small, 23 cm" },
                { type: "Thin", price: 17, size: "Medium, 30 cm" },
                { type: "Thin", price: 22, size: "Large, 35 cm" },
            ],
            id: "WJX9dW58zb5a02-yfbSwc",
        },
        {
            title: "New Orleans",
            composition: "Corn, Grilled Chicken, Mushroom, Green Pepper, Garlic Sauce, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_70c8a9940967f04db780cde16feeeccf.jpg",
            price: 10,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 10, size: "Small, 23 cm" },
                { type: "Traditional", price: 15, size: "Medium, 30 cm" },
                { type: "Traditional", price: 21, size: "Large, 35 cm" },
                { type: "Thin", price: 10, size: "Small, 23 cm" },
                { type: "Thin", price: 15, size: "Medium, 30 cm" },
                { type: "Thin", price: 21, size: "Large, 35 cm" },
            ],
            id: "mUaeVzpr3vQATXbD1lL0p",
        },
        {
            title: "Chicken Buffalo",
            composition: "Ranch sauce, Chicken Poppers, Ham, Buffalo Sauce, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_867e3e360e53589e9c9d53b3820786c9.jpg",
            price: 12,
            subcategory: ["chicken", "hot"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 18, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 18, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "5yREPOWxOJUcjyjBHiMsE",
        },
        {
            title: "Chicken Mushroom",
            composition: "Mushroom sauce, Grilled Chicken, Pickles, Mushroom, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_e3a441242ae92df92dd6fb3b523d2fb1.jpg",
            price: 12,
            subcategory: ["chicken"],
            category: "pizza",
            variations: [
                { type: "Traditional", price: 12, size: "Small, 23 cm" },
                { type: "Traditional", price: 19, size: "Medium, 30 cm" },
                { type: "Traditional", price: 23, size: "Large, 35 cm" },
                { type: "Thin", price: 12, size: "Small, 23 cm" },
                { type: "Thin", price: 19, size: "Medium, 30 cm" },
                { type: "Thin", price: 23, size: "Large, 35 cm" },
            ],
            id: "zkhD85NasHA7kGgzqYu7Y",
        },
    ],

    sides: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_305cb7fe83f207951f2fa33840d51938.jpg",
            title: "Pepperoni Rolls",
            composition: "8 Rolls | Pepperoni, Ranch sauce + 1 Pizza sauce",
            price: 9,
            category: "sides",
            id: "FZv6qE3czddyXcsPNugrG",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_1490edc2b75e6b911ff0688ef21cf75e.jpg",
            title: "Cheddar Rolls",
            composition: "8 Rolls | Cheddar, Garlic sauce + Pizza sauce",
            price: 9,
            category: "sides",
            id: "8VV_biUJlxgO0O2IffnHJ",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_3228ebb7bb5d266f598cc27e2a7af05c.jpg",
            title: "Chicken Rolls",
            composition: "8 Rolls | Grilled Chicken, Pickles, Mozzarella, Ranch Sauce + 1 Pizza sauce",
            price: 9,
            category: "sides",
            id: "O7J-mgCfR2ozRkdqNTU5C",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f307d270999251d9e39730bc930f3cae.jpg",
            title: "Spicy Chicken Rolls",
            composition: "8 Rolls | Grilled Chicken, Jalapeno, Mozzarella, Ranch sauce + 1 Pizza sauce",
            price: 9,
            category: "sides",
            id: "6XN5XJiPROXkak5EU0cjg",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_d1d450cddca70334681bcb47a9ef15cb.jpg",
            title: "Cheddar Cheese Sticks",
            composition: "1 Pizza Sauce, 1 Garlic Sauce",
            price: 9,
            category: "sides",
            id: "fsH2cBcOmsHUW3xC3VyMb",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_778eeba1701e27a7e588448fa59274b8.jpg",
            title: "Cheese Sticks",
            composition: "Garlic Sauce, Pizza Sauce",
            price: 7,
            category: "sides",
            id: "tAdon4jRY33T7ZLIi0sT5",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_9899000d4a87b161975f77d17ade89f2.jpg",
            title: "Ham and Mushroom Sticks",
            composition: "Garlic Sauce, Ham, Mushroom, Mozzarella",
            price: 9,
            category: "sides",
            id: "NMSCI_Jks9Uw9n0ASSggu",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_437e1050c4734d2a567df699308fa2c7.jpg",
            title: "Sesame Cheese Sticks",
            composition: "Garlic Sauce, Mozzarella, Sesame",
            price: 8,
            category: "sides",
            id: "LmUbRtShRGFV4sWl0rIJx",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_2b328d7ec01601154c30030b95c1e51b.jpg",
            title: "Garlic Sticks",
            composition: "Garlic Sauce, Pizza Sauce",
            price: 3,
            category: "sides",
            id: "g-T5qOh1aGE8vhVfdcrMK",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ad11ce5af9801f29710eec91449dd295.jpg",
            title: "Chicken Poppers BBQ",
            composition: "150 grams",
            price: 6,
            category: "sides",
            id: "am5-K4n64G7BegMvwWZoT",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_225e3de38654e53c1da1ef0022bef1c2.jpg",
            title: "Kalzone with Grilled Chicken and Mushroom",
            composition: "Grilled Chicken, Mushroom, Garlic Sauce, Mozzarella",
            price: 6,
            category: "sides",
            id: "yYqpNE4R6TUOV6MsLGJGW",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_3b1677d0e8d3aaba0b33fd3e465063f5.jpg",
            title: "Kalzone with Pepperoni and Italian Sausage",
            composition: "Pepperoni, Italian Sausages, Garlic Sauce, Mozzarella",
            price: 6,
            category: "sides",
            id: "2Zx4jxh4QrW0bgGRcjpzl",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_03f7fd6f5ef482929b803c762fca496d.jpg",
            title: "Cheese Twists",
            composition: "1 Pizza Sauce, 1 Garlic Sauce",
            price: 10,
            category: "sides",
            id: "kdgUp2zTgsmbNOpQYf4yP",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_40fdeaa67ec64a8b72eb0c38d3802403.jpg",
            title: "Chicken Wings",
            composition: "With BBQ or Buffalo sauce (250 g)",
            price: 9,
            category: "sides",
            id: "9iyX49FajRbm4ARaQYvXA",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_1a262425388a3bc72e78973c59c5231b.jpg",
            title: "Potato Wedges",
            composition: "200 grams",
            price: 4.9,
            category: "sides",
            id: "4KFYnIxCe1n5CTPvEzM-G",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_461c8b5494d24b06508b527ff271292f.jpg",
            title: "Chicken Poppers",
            composition: "150 grams",
            price: 6,
            category: "sides",
            id: "FyzDz2x93NuoLfDz8xzKJ",
        },
    ],

    pasta: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_a288bc9c11d13c2acf5a84267b407308.jpg",
            title: "Super Papa's Pasta",
            composition: "Spaghetti, Pepperoni, Ham, Italian Sausage, Green Peppers, Mushrooms, Mozzarella, Pizza Sauce",
            price: 9,
            category: "pasta",
            id: "FHMPJoS82m0RYMQq6iB5h",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_2cc11cf0b81ea54520d03f9fc3abfbc3.jpg",
            title: "Chicken Ranch Pasta",
            composition: "Spaghetti, Grilled Chicken, Mushroom, Ranch Sauce, Mozzarella",
            price: 9,
            category: "pasta",
            id: "zZJgLH7n4Ki_81LWnM_qt",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_a577e417ead4d7702c65acacb3745b8d.jpg",
            title: "Mama Pasta",
            composition: "Spaghetti, Parmesan, Oregano, Pizza Sauce, Mozzarella",
            price: 7,
            category: "pasta",
            id: "fKffI5lk0LMW6whzcHBs8",
        },
    ],

    salads: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_27375b9f0f16f820c97ce9d3c54ed8e8.jpg",
            title: "Caesar Salad",
            composition: "Grilled Chicken, Iceberg Lettuce, Croutons, Tomato, Parmesan, Caesar Dressing",
            price: 9,
            category: "salads",
            id: "dnRddjSK2MyvNe5h20rNB",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_5791f4ffe0062ee2f97b366f079ce9e8.jpg",
            title: "Greek Salad",
            composition: "Cucumber, Tomato, Iceberg Lettuce, Black Olive, Feta Cheese, Italian Dressing, Oregano, Green Pepper",
            price: 6,
            category: "salads",
            id: "0jf9vuFBlBIoG2jjSBUn2",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_4cffa0ed49e334a46557e0953fcaf7b2.jpg",
            title: "Garden Salad",
            composition: "Iceberg Lettuce, Cucumbers, Tomatoes, Black Olives, Green pepper, Italian Sauce, 1 garlic breadstick",
            price: 5,
            category: "salads",
            id: "exL_CFztVJmGQnnUY5-Ia",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_7001464aefa6de30e1b1342322f645c2.jpg",
            title: "Tuna Salad",
            composition: "Tuna, Iceberg Lettuce, Black Olive, Corn, Cucumber, Italian Dressing",
            price: 8,
            category: "salads",
            id: "PK1RYCW7elEyIqRFrABQs",
        },
    ],

    drinks: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_d33f50ba9123e71329db8e94b22ce050.jpg",
            title: "Coca Cola 500ml",
            price: 2.5,
            category: "drinks",
            variety: [],
            id: "mOELfoWWgVpv80bcDqjjq",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_acc0ad8e2b510ede462e9b05eea4945f.jpg",
            title: "Coca-Cola Zero Sugar 500ml",
            price: 2.5,
            category: "drinks",
            variety: [],
            id: "-1h3P3_WohQhZal5DDEXF",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_a51ee83e40de114f24b48fe5ba457ac2.jpg",
            title: "Sprite 500ml",
            price: 2.5,
            category: "drinks",
            variety: [],
            id: "hVq6OZcH0dzGMoMqfkyve",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_112470ad2d37edfe04e753674c1e9eb3.jpg",
            title: "Fruit Juices - Cappy (500 ml)",
            price: 1.5,
            category: "drinks",
            variety: ["Orange", "Multivitamin", "Sour Cherry", "Peach", "Apple"],
            id: "ngXXdWf0-bSFEvEzkcijK",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_51b81194a6d9691903077b4ee059b15d.jpg",
            title: "Yogurt Drink 200ml",
            price: 1.5,
            category: "drinks",
            variety: ["With Bread", "Regular"],
            id: "wS3k04rZQ5JOlGGH_YC6Q",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f6ad66d40305f0f8ebc33aa25fc95b43.jpg",
            title: "Fanta 500ml",
            price: 2.5,
            category: "drinks",
            variety: [],
            id: "wWIWoI2bPKXivuKxQFid0",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_4511509d48418ecaabe6fe83d55e4211.jpg",
            title: "Still Water 500ml",
            price: 1,
            category: "drinks",
            variety: [],
            id: "pagGDP6yMZ31FSrW6hHqr",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_afa0f635cc88cc071ad0294099723479.jpg",
            title: "Sparkling Water 500ml",
            price: 1,
            category: "drinks",
            variety: [],
            id: "kC6EeVDTMr0K9CPRMQeIU",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_b66e27027a67e049ccfc650c42f62938.jpg",
            title: "Fuse Tea (500 ml)",
            price: 3,
            category: "drinks",
            variety: ["Peach", "Lemon", "Mango Pineapple"],
            id: "IH0kTa907i600LNrOCAhW",
        },
    ],

    desserts: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ad0d3c2bd3dfd02d2291c92b3da4b380.jpg",
            title: "Tiramisu",
            price: 7,
            id: "LqUOx499IGm5KS69gzWCW",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_1586374dc56f6447a659ff607eb2ff25.jpg",
            title: "Chocolate Soufflé",
            price: 5,
            id: "Rl_H4YpvxFumTx-sND0V5",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_cea02388c7e67f4ca204e3ee470e819f.jpg",
            title: "Ice Cream",
            price: 2,
            id: "mK-6aVd-B5Ndw3DrHCvQF",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_e8b93fb140ef803710e0a6974ac10d9b.jpg",
            title: "San Sebastian",
            price: 8,
            id: "HtHwvFbY5z5l2E0V4q5bZ",
        }
    ],

    sauces: [
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_ecda9572693fc6a263ef917c0bc003e7.jpg",
            title: "Ranch Sauce",
            price: 0.8,
            category: "sauces",
            id: "R6iGC1C98qT7Y4EDn9A5x",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_731d5122d8dc1f4f267ac28c5beaf1d8.jpg",
            title: "Barbecue Sauce",
            price: 0.8,
            category: "sauces",
            id: "RfbfLtlrFUnPIZYrjkP94",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_51dc048ab0369b7f4589493eb65318ba.jpg",
            title: "Garlic Sauce",
            price: 0.8,
            category: "sauces",
            id: "VJJtPIERk_JdyXCxqyWES",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_b36655ac7ff9b64d2e066e1f69810621.jpg",
            title: "Buffalo Sauce",
            price: 0.8,
            category: "sauces",
            id: "rdKpnzxGTjLMjNtq2lmn",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_e3462215fb4a5ff50bdfd97ba54b59db.jpg",
            title: "1000 Island Sauce",
            price: 0.8,
            category: "sauces",
            id: "-yEn5O7SS7e3bjaVkcpRP",
        },
        {
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_7ea41c9b4d3ff7642e4af084dbe38ff5.jpg",
            title: "Pizza Sauce",
            price: 0.8,
            category: "sauces",
            id: "XWIUvwpr7HxfPyHd1xPwx",
        },
    ],

    papadias: [
        {
            title: "Italian Papadias",
            composition: "Pizza Sauce, Italian Sausage, Pepperoni, Mozzarella, Parmesan, Italian spices",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_4f6b29a2063afa150b3793240a97988e.jpg",
            price: 9,
            category: "papadias",
            id: "1SfcpmSLl3ot4mc7Z-7ql",
        },
        {
            title: "Cheddar Mexican Papadias",
            composition: "Pizza sauce, Green Pepper, Grilled Chicken, Mozzarella, Cheddar, Jalapeño",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_5cf3c3909a3c5fa466dc6ed16c5836cc.jpg",
            price: 9,
            category: "papadias",
            id: "cbz3BHsR1j8F7J4mmjx9a",
        },
        {
            title: "Double Cheddar Cheeseburger Papadias",
            composition: "1000 Island sauce, Beef, Tomato, Mozzarella and Cheddar Cheeses",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_978162a01eda0042ae1707bf563ac3e0.jpg",
            price: 9,
            category: "papadias",
            id: "esxQUoV8zl2Mswz6eMwkC",
        },
        {
            title: "New Orleans Papadias",
            composition: "Garlic Sauce, Green Pepper, Grilled Chicken, Corn, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_2bed10a8aa16b5835f6db36b505ba0fa.jpg",
            price: 9,
            category: "papadias",
            id: "nusHPUToAxJyK5zQOLBaU",
        },
        {
            title: "Chicken Buffalo Papadias",
            composition: "Ranch Sauce, Grilled Chicken, Tomato, Mozzarella, Buffalo Sauce",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_13f62c1a64a60fbfd55cac0579f3d80e.jpg",
            price: 9,
            category: "papadias",
            id: "Lmz36v0bmKw7moWxD9Oak",
        },
        {
            title: "Spicy Chicken Ranch Papadias",
            composition: "Ranch Sauce, Grilled Chicken, Mushroom, Tomato, Jalapeño, Mozzarella",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_19c1323adbcb9a595018f5979a862204.jpg",
            price: 9,
            category: "papadias",
            id: "H3WlBKayVTVKvh-EhVUIO",
        },
        {
            title: "Chicken BBQ Papadias",
            composition: "Grilled Chicken, Mushroom, Mozzarella, Barbecue Sauce",
            img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f7db43402b2cd4bda0a88b5028bc1dfd.jpg",
            price: 9,
            category: "papadias",
            id: "JNHsV9QGKzfZOnuqxOV85",
        },
    ],
};

let allProducts = [];

for (const category in food) {
    allProducts = allProducts.concat(food[category]);
}

const locations = [
    {
        name : 'Elmler',
        address: 'Huseyn Javid 32',
        time: 'Mon-Sun: 11AM-11PM Last dine in order: 10:30PM Last take away order: 10:45PM',
    },
    {
        name: 'Khirdalan',
        address: 'Haji Zeynalabdin Taghiyev 5 ',
        time: 'Mon-Sun: 11AM-11PM Last dine in order: 10:30PM Last take away order: 10:45PM',
    },
    {
        name: 'Crescent mall',
        address: 'Neftçilər prospekti 64-72',
        time: 'Mon-Sun: 10AM-11PM',
    },
    {
        name: 'Sahil',
        address: 'Nizami street. 106 A',
        time: 'Mon-Sun: 11AM-11PM; ; Last dine in order: 10:30PM; ; Last take away order: 10:45PM',
    },
    {
        name: 'Ganclik',
        address: '1110 Hasan Aliyev , 82Q',
        time: 'Mon-Sun: 11AM-11PM Last dine in order: 10:30PM Last take away order: 10:45PM',
    },
    {
        name: 'Adjemi',
        address: 'Cavadxan street 15c',
        time: 'Mon-Sun: 11AM - 5.30AM Last dine in order: 10:30PM Last take away order: 10:45PM',
    },
    {
        name: 'Shopping center Park Bulvar',
        address: 'Neftchiler ave. 92',
        time: 'Mon-Sun: 10AM-10PM',
    },
    {
        name: 'Ahmedli',
        address: 'Almaz İldirimli street. 68',
        time: 'Mon-Sun: 12PM-9PM',
    },
];
